name: CI Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  # =====================================================
  # JOB 1: TEST
  # =====================================================
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '220'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm Install

      # Run Jest tests with coverage
      - name: Run tests with coverage
        run: npm test -- --coverage


  # =====================================================
  # JOB 2: SONARQUBE
  # =====================================================
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    # SonarQube runs only when test job succeeds
    needs: test

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm Install

      # Generate coverage report
      - name: Run tests with coverage
        run: npm test -- --coverage

      # SonarQube analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=cicd-quality-assignment
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.test.inclusions=tests/**
            -Dsonar.exclusions=**/node_modules/**
